name: Deploy to GitHub Pages
on:
  push:
    branches:
      - marketing-landing-page

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./